export const dummyDate = {
  turkish: {
    language: "tr",
    navcols: ["HAKKIMDA", "YAZILARIM"],
    about: {
      title: "HAKKIMDA",
      desc: "Selamlar, yüksek motivasyonlu ve çoğunlukla kendi kendine öğrenen bir front-end geliştiriciyim. Eğitimimi Türkçe öğretmeni olarak bitirdim ve halen öğretmen olarak çalışıyorum. Ama yazılımın benim tutkum olduğunu anladım. Çok iyi ve sürekli gelişen bir yazılımcı olmak istiyorum. Öğrenmeye olan tutkumu geliştirerek her zaman sağlam ve faydalı bilgiler edinmeye çalışırım. Eğitimin yaşam için olduğuna inanıyorum. İngilizceyi kendim öğrendim. Yazılımı çoğunlukla kendim öğrendim ve tabii ki öğrenmeye devam ediyorum. 2021 için özel hedefim olan Almanca öğrenmek için emin adımlarla ilerliyorum.",
    },
    articles: [
      {
        id: "0154",
        img:null,
        title: "Bla bla bla bla mla cla sla ala",
        text: " Blaa bla Blaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa bla",
        // date: new Date(),
        readMin: 5,
        tags: ["bla", "blue", "gla"],
        clapCount: 50,
        shareTwt: null,
        shareLnkd: null,
      },
      {
        id: "0155445",
        title: "Blla ala",
        text: " Blaa bla Blaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa bla",
        // date: new Date(),
        readingMin: 5,
        tags: ["bla", "blue", "gla"],
        clapCount: 50,
        shareTwt: null,
        shareLnkd: null,
      },
    ],
  },
  deutsch: {
    language: "de",
    navcols: ["ÜBER MICH", "DIE ARTIKEL"],
    about: {
      title: "ÜBER MICH",
      desc: "Schöne Grüße Ich bin ein hochmotivierter und meist selbstlernender Front-End-Entwickler. Ich habe mein Studium als Türkischlehrer abgeschlossen und arbeite immer noch als Lehrer. Aber mir wurde klar, dass meine Leidenschaft Software war. Ich möchte ein sehr guter und sich ständig weiterentwickelnder Softwareentwickler sein. Ich versuche immer, solide und nützliche Informationen zu erhalten, indem ich meine Leidenschaft für das Lernen weiterentwickle. Ich glaube, Bildung ist fürs Leben. Ich habe selbst Englisch gelernt. Ich habe die Software meistens selbst gelernt und lerne natürlich weiter. Ich mache feste Schritte, um Deutsch zu lernen, was mein spezifisches Ziel für 2021 ist.",
    },
    articles: [
      {
        id: "0154",
        img:null,
        title: "Bla bla bla bla mla cla sla ala",
        text: " Blaa bla Blaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa bla",
        // date: new Date(),
        readMin: 5,
        tags: ["bla", "blue", "gla"],
        clapCount: 50,
        shareTwt: null,
        shareLnkd: null,
      },
      {
        id: "0155445",
        title: "Blla ala",
        text: " Blaa bla Blaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa bla",
        // date: new Date(),
        readingMin: 5,
        tags: ["bla", "blue", "gla"],
        clapCount: 50,
        shareTwt: null,
        shareLnkd: null,
      },
    ],
  },
  english: {
    language: "en",
    navcols: ["ABOUT ME", "ARTICLES"],
    about: {
      title: "ABOUT ME",
      desc: "Greetings, I am a highly motivated and mostly self-learning front-end developer. I finished my studies as a Turkish teacher and still work as a teacher. But I realized that software was my passion. I want to be a very good and constantly developing software developer. I always try to get solid and useful information by developing my passion for learning. I believe education is for life. I learned English myself. I have mostly learned the software myself and of course I keep learning. I am taking firm steps to learn German, which is my specific goal for 2021.",
    },
    articles: [
      {
        id: "0154",
        img:null,
        title: "Bla bla bla bla mla cla sla ala",
        text: " Blaa bla Blaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa bla",
        // date: new Date(),
        readMin: 5,
        tags: ["bla", "blue", "gla"],
        clapCount: 50,
        shareTwt: null,
        shareLnkd: null,
      },
      {
        id: "0155445",
        title: "Blla ala",
        text: " Blaa bla Blaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa blaBlaa bla",
        // date: new Date(),
        readingMin: 5,
        tags: ["bla", "blue", "gla"],
        clapCount: 50,
        shareTwt: null,
        shareLnkd: null,
      },
    ],
  },
};
